version: '2'
services:
    mongodb:
        image: mongo:4.0.2
        container_name: mongodb
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/cms/mongodb/:/data/db/
