version: '2'
services:
    elasticsearch:
        image: elasticsearch:6.8.3
        container_name: elasticsearch
        environment:
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        image: kibana:6.8.3
        container_name: kibana
        ports:
            - 5601:5601
