version: '2'
services:
    elasticsearch-v7:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
        container_name: es
        environment:
            - node.name=es
            # - discovery.type=single-node
            - cluster.initial_master_nodes=es1,es2,es3
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            # - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - esnet

    elasticsearch-v6:
        image: elasticsearch:6.8.3
        container_name: elasticsearch
        environment:
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
        ports:
            - 9200:9200
            - 9300:9300
    kibana-v6:
        image: kibana:7.4.1
        container_name: kibana
        ports:
            - 5601:5601

    elasticsearch-v5:
        image: elasticsearch:5.6.13
        # volumes:
        #     - ~/volumes/jhipster/cms/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
        environment:
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
